### ISSUE TITLE
[BUG] Voice Record not saving to PROD

### ISSUE THREAD

**Issue by TodorBachvarov** [rokwire/content-building-block#102]
Origin: https://github.com/rokwire/illinois-app/issues/4033. 
When we perform this request on PROD: url/content/voice_record we receive an error: Reason: 500 Error uploading voice record. When we perform the same request on DEV and TEST it works fine (status 200).

**Comment by pascoem** [comment]
Hello @stefanvit .  Per your request:


- The user `vburgett` has no outstanding discrepencies in her Authman account for Rokwire permissions.
	- If there is a specific policy group that you are aware of for Content permissions, please share so I might do a more in-depth review if needed.
- The Test and Prod versions of the users' audio S3 buckets are configured the same for both permissions and properties.
	- This includes denying any HTTP requests.  The buckets are HTTPS only, if that matters.
- The Test bucket has a folder named names-records with one m4a object in it.  The Prod bucket does not contain anything.
	- The object has one version, last modified `May 15, 2024, 23:53:55 (UTC-05:00)`.

**Comment by stefanvit** [comment]
> Hello @stefanvit . Per your request:
> 
> * The user `vburgett` has no outstanding discrepencies in her Authman account for Rokwire permissions.
>   
>   * If there is a specific policy group that you are aware of for Content permissions, please share so I might do a more in-depth review if needed.
> * The Test and Prod versions of the users' audio S3 buckets are configured the same for both permissions and properties.
>   
>   * This includes denying any HTTP requests.  The buckets are HTTPS only, if that matters.
> * The Test bucket has a folder named names-records with one m4a object in it.  The Prod bucket does not contain anything.
>   
>   * The object has one version, last modified `May 15, 2024, 23:53:55 (UTC-05:00)`.

Thank you @pascoem! I will keep looking for resolving this issue!

**Comment by stefanvit** [comment]
> * discrepencies


Sure, here's the translated text:

Hi Mike,

What I'm asking you about is not related to the burger account, but rather the AWC account, which manages the upload and download in the  S3 audio bucket.

For reference, the dev (who successfully uploads to the following bucket: rokwire-users-audios). Please, when you have a chance, check if the account for Test and Prod has the rights to upload and download on Test and Prod.

What we are noticing is that it doesn't have the rights and returns this error 403:

2024/05/21 12:01:55 Error uploading voice record: AccessDenied: Access Denied

Everything seems to be fine in the code, so if you please check these configurations on Test and Prod.

cc: @pmarkhennessy
